db_class_name : com.mysql.cj.jdbc.Driver
db_url : jdbc:mysql://localhost:3307/plist?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
db_username : plistuser
db_password : zerobase
ddl_auto : update
database : mysql
youtube_data_api_key: AIzaSyCVNaYPyTTGFbu2AyMwEnhnVSv9d5p5Ehs